[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["Risen <yerokhinyaroslav@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
playwright = "^1.40.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
